---

- name: Configuring address-matching environment
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Execute Docker Down
      shell: $(docker-compose build ; sh docker-compose up -d)
      become_method: sudo
      become_user: ubuntu
